name: Build and Deploy DAX Docs
on: [workflow_dispatch]
jobs:
  build:
    name: Build DAX Docs
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [14.x]
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
      - name: Install Dependencies
        run: npm ci
      - run: npm run build
      - name: Store Site Artifact
        uses: actions/upload-artifact@v2
        with:
          name: dax-docs-site
          path: |
            _site
          retention-days: 30
  deploy:
    name: Deploy DAX Docs
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Download DAX Docs artifact
        uses: actions/download-artifact@v2
        with:
          name: dax-docs-site
      - name: Deploy to GH pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          publish_dir: ./
          github_token: ${{ secrets.GITHUB_TOKEN }}